title: Ghaida Alsenani

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ghaidasenani.github.io # the base hostname & protocol for your site, e.g


author-img: IMG_9677.JPG # add your photo
about-author:  Always hungry to keep learning. # add description

social-github: GhaidaSenani # add your Github handle
social-linkedin: ghaidaalsenani # add your Linkedin handle
social-email:  ghaidasenani@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics
# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
