# Permalinks
permalink:           pretty

# Setup
title:               Ghaida Alsenani
tagline:             
url:                 http://GhaidaSenani.github.io
paginate:            2
baseurl:             ""

# Assets
#
# 
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ghaida Alsenani
  url:               https://twitter.com/ghaidaalsenani
  email:             ghaidasenani@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/GhaidaSenani

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
 
  Feed: '/index.html'
